# Generated by Django 3.0 on 2019-12-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='lng',
        ),
    ]
